version: "3.8"

services:
  salesflow_php:
    build: .
    container_name: salesflow_php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - salesflow_db
      - mailhog
      - redis
    environment:
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
  salesflow_db:
    image: mysql:8.0
    container_name: salesflow_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesflow
      MYSQL_USER: salesflow
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  redis:
    image: redis:alpine
    container_name: salesflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  queue_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salesflow_queue_worker
    restart: unless-stopped
    depends_on:
      - salesflow_php
      - redis
    volumes:
      - .:/var/www/html
    command: [ "/bin/sh", "-c", "sh queue_worker_entrypoint.sh" ]
volumes:
  db_data:
