version: "3.8"

services:

  salesflow_backend:
    build: ./backend
    container_name: salesflow_backend
    restart: unless-stopped
    depends_on:
      - salesflow_db
      - redis
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: salesflow_db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: salesflow
      MYSQL_USER: salesflow
      MYSQL_PASSWORD: secret
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor

  salesflow_frontend:
    build: ./frontend
    container_name: salesflow_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - salesflow_backend

  salesflow_db:
    image: mysql:8.0
    container_name: salesflow_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesflow
      MYSQL_USER: salesflow
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: salesflow_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:alpine
    container_name: salesflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  queue_worker:
    build: ./backend
    container_name: salesflow_queue_worker
    restart: unless-stopped
    depends_on:
      - salesflow_backend
      - redis
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    command: [ "/bin/sh", "-c", "php artisan queue:work" ]

volumes:
  db_data:
